#!/usr/bin/env perl
use IO::File;

my $include_path = "/usr/include/bullet";
my @exclude_pat = qw{
  autogenerated/bullet.h
  LinearMath/btConvexHull.h
  vectormath
  XmlWorldImporter
  BulletCollision/Gimpact
  BulletDynamics/Featherstone
  BulletDynamics/MLCPSolvers
};

my $hdrs_str = `cd $include_path && find . -name "*.h"`;
my @hdrs = split(/\n/, $hdrs_str);
my $ofile = new IO::File("headers.cpp", "w");
outer:
for my $hdr (@hdrs) {
  $hdr =~ s/^.\///;
  for my $s (@exclude_pat) {
    if (index($hdr, $s) != -1) {
      next outer;
    }
  }
  print $ofile "#include <$hdr>\n";
}
system("gccxml -I$include_path headers.cpp -fxml=bullet-api.xml");
