
all:
	./run.sh

clean:
	rm -f *.log *.log2 *.log2h *.exe *.o *.class *.so *.pyc
	rm -rf gen
	rm -f *.px.cc
	find . -name ".pxc" -exec rm -rf {} \; 2> /dev/null; exit 0
	rm -f DONE
	rm -f *.html *.js *.data *.mem

