def test_c1(num):
  obj, sum = cfoo(), 0
  for i in range(num):
    sum = obj.faddint(sum, i)
  return sum

def test_c2(num):
  obj, sum = cfoo(), 0
  for i in range(num):
    sum += obj.faddlenstr(str(i), str(i))
  return sum

def test_c3(num):
  obj, sum = cfoo(), 0
  for i in range(num):
    sum += obj.faddlensref(str(i), str(i))
  return sum

def test_p1(num):
  obj, sum = pfoo(), 0
  for i in range(num):
    sum = obj.fadd(sum, i)
  return sum

def test_p2(num):
  obj, sum = pfoo(), 0
  for i in range(num):
    sum += obj.faddlen(str(i), str(i))
  return sum

pytiming5::do_test{"test_c1",100}	4500
pytiming5::do_test{"test_c1",100}	4500
pytiming5::do_test{"test_c1",100}	4500
pytiming5::do_test{"test_c2",100}	2000
pytiming5::do_test{"test_c2",100}	2000
pytiming5::do_test{"test_c2",100}	2000
pytiming5::do_test{"test_c3",100}	2000
pytiming5::do_test{"test_c3",100}	2000
pytiming5::do_test{"test_c3",100}	2000
pytiming5::do_test{"test_p1",100}	4500
pytiming5::do_test{"test_p1",100}	4500
pytiming5::do_test{"test_p1",100}	4500
pytiming5::do_test{"test_p2",100}	2000
pytiming5::do_test{"test_p2",100}	2000
pytiming5::do_test{"test_p2",100}	2000
